"""empty message

Revision ID: 0cf76049f35b
Revises: dd622e6b8e37
Create Date: 2024-05-31 03:30:22.151345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cf76049f35b'
down_revision = 'dd622e6b8e37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flight', schema=None) as batch_op:
        batch_op.drop_column('updated')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flight', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
