"""empty message

Revision ID: 3b6192bcca9a
Revises: e67964e43f09
Create Date: 2024-05-31 03:23:47.068552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b6192bcca9a'
down_revision = 'e67964e43f09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transportation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guest_id', sa.Integer(), nullable=False),
    sa.Column('transport_type', sa.String(length=100), nullable=False),
    sa.Column('transport_details', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['guest_id'], ['guest.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transportation')
    # ### end Alembic commands ###
