"""empty message

Revision ID: dd622e6b8e37
Revises: 3b6192bcca9a
Create Date: 2024-05-31 03:27:22.315125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd622e6b8e37'
down_revision = '3b6192bcca9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest', schema=None) as batch_op:
        batch_op.drop_column('transportation')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transportation', sa.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
